### ISSUE TITLE
[Crash]: java.lang.NullPointerException

### ISSUE THREAD

**Issue by TeamPeril** [Fuzss/respawninganimals#10]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.4

### Mod Version (Required)

v6.0.0

### Notes (Required)

1. I run a server 24/7. 
2. One time during the middle of the night, the server crashed.
3. I'm unable to reproduce it in a timely manner due to the nature of the crash.
4. Its a null pointer exception, so adding a check to that location should be an easy fix.

### Crash Report (Required)

https://gist.github.com/TeamPeril/20707b9e0a270a33344138722dda40fa

**Comment by Fuzss** [comment]
Fixed in v8.1.0. 1.19.4 is no longer supported.
