### ISSUE TITLE
[Bug]: Mod Not Generating Config Files

### ISSUE THREAD

**Issue by Aizria** [Fuzss/respawninganimals#21]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2 - Forge 40.2.9

### Mod Version (Required)

3.0.1

### Notes (Required)

When loaded by Forge for the first time, or on any subsequent times thereafter, the mod does not generate any configuration files.

**Comment by SurrealNautilus** [comment]
I have the same issue. 

I need to create a blacklist to prevent pigs, cows, and sheep from despawning. But I can't find either MOD_ID-client.toml, MOD_ID-common.toml, or MOD_ID-server.toml.

I play it locally. I only find one file in Config called respawninganimals-server.toml.

Maybe I'm dumb and I'm missing something, haha.

I would greatly appreciate it if you could see what the problem might be. Thank you!

Mod Loader: Forge
Minecraft version: 1.20.1 
Mod version: v8.1.1

**Comment by Fuzss** [comment]
The blacklist is a tag which needs to go in a data pack. There is no config file available for his mod. The description on the mod page is a template.
