### ISSUE TITLE
Chickens spawning ANYWHERE [Bug]: 

### ISSUE THREAD

**Issue by Krocodialion** [Fuzss/respawninganimals#23]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.1.1

### Notes (Required)

Chickens spawn in the nether, in caves, the end, just EVERYWHERE.
I uninstalled the mod and they stopped spawning, but then I reinstalled and it started again
It doesn't really matter to me but I just thought i'd report it.

**Comment by mrGRINCH** [comment]
Had the same problem on 1.20.1 Fabric. Hundreds of chickens in caves.

**Comment by Fuzss** [comment]
Same as #24.
Should be fixed in v8.2.0.
