### ISSUE TITLE
[Bug]: Striders spawning non-stop into the thousands.

### ISSUE THREAD

**Issue by mrGRINCH** [Fuzss/respawninganimals#24]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.1

### Notes (Required)

I made a simple Hoglin farm in the nether and was sitting at build limit above the nether roof afk'ing and noticed the TPS had dropped to 10 and so I checked and Striders were spawning non-stop into the thousands.

I killed them all with the /kill command waited 20 seconds and TPS was down again so I used the kill command again and killed thousands more. They just spawn non-stop into the thousands.

Removing the mod fixed the issue.

Where they were spawning was outside of the despawn sphere. But I think they spawn anyway right because they're passive mobs?

**Comment by Fuzss** [comment]
Can you reproduce the issue with just Respawning Animals + dependencies?

**Comment by Fuzss** [comment]
Should be fixed in v8.2.0.
