### ISSUE TITLE
[Bug]: Respawning Animals doesn't despawn Toretoises from Quark

### ISSUE THREAD

**Issue by Thombias** [Fuzss/respawninganimals#25]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.18.2

### Mod Version (Required)

v3.0.1

### Notes (Required)

Hi there, i've been playing around a bit in a survival test world for my upcoming modpack in hopes of spotting some issues along the way and it appears i have found one.

Today i kept wondering why my fps just die whenever i look in certain directions and my tps were consistently hitting more than 50ms, whereas just a day before everything was running fine. I opened up the F3 menu and the entity count in there says there are more than 400 entities rendered whenever i look down, so i enabled cheats and went to spectator mode, and that was where i finally found out what was causing the immense lag.
The underground seemed to have continously spawned Toretoises from the mod Quark but never despawned any of them, resulting in spots being filled to the brim with them. I even tried unloading the chunks but that didn't despawn them either.
According to the Quark Wiki these are a neutral mob though, so i'm wondering what exactly went wrong there? I thought this mod should only affect passive mobs, right?

Any chance for this to get fixed for the 1.18.2 version? I was thinking about putting them in the blacklist but i'm somehow missing the config file in the serverconfig for my world file. Does it just not exist for the 1.18.2 version?

![2023-10-10_19 04 37](https://github.com/Fuzss/respawninganimals/assets/46842890/80e15dd0-32b1-48aa-ba5c-39752781497e)
![2023-10-10_19 05 33](https://github.com/Fuzss/respawninganimals/assets/46842890/5672c15c-f9af-4473-aa65-65c3da126eb2)

**Comment by Fuzss** [comment]
Should be fixed in v3.1.0.
