### ISSUE TITLE
[Bug]: Tamed Animals Still Despawn If Not Name Tagged

### ISSUE THREAD

**Issue by AngelsLikeChopSuey** [Fuzss/respawninganimals#26]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

8.1.1

### Notes (Required)

This happened on a server I was on using the mod and I recreated the issue in a creative mode superflat world. If you go a big distance away from the animal, it will despawn. This can seemingly only be prevented with nametags. I'm on Forge, but I also have sinytra connector installed, if that means anything.

**Comment by Fuzss** [comment]
What animal(s) did you tame?

**Comment by Fuzss** [comment]
So the original implementation only made a tamed animal persistent in the moment when it is tamed.
I've now included something additional, that checks if tamed animals are persistent on every tick, so this cannot be missed as easily anymore. Please reopen if this is still an issue in v8.2.0.
