### ISSUE TITLE
[Bug]: Config file not created

### ISSUE THREAD

**Issue by Zothen1973** [Fuzss/respawninganimals#28]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.2.0

### Notes (Required)

There is no config file/folder in the config folder. Referring to the description there should be one.

**Comment by Fuzss** [comment]
The mod no longer has a config file. All configuration is possible via two the game rules:
- `animalMobCap` for setting how many animals must be in the world for the spawning algorithm to stop spawning new ones
- `persistentAnimals` for toggling the mod mechanics as a whole
There also is an additional entity type tag:
- `persistent_animals` for animals that will not behave just like in vanilla, so no despawning or respawning, and no counting towards the mob cap

The mod page description is currently out of date.
