### ISSUE TITLE
[Suggestion]: Tag to make "persistent" mobs no longer persistent

### ISSUE THREAD

**Issue by ZerbieSlug** [Fuzss/respawninganimals#29]
### Suggestion (Required)

While we already have a tag that allows for mobs to be persistent, there doesn't seem to be a tag that does the opposite.

I'm only suggesting this as while testing out the Alex's Caves mod, there's a certain mob that, despite being an animal that spawns "naturally", it cannot despawn whatsoever. Would be neat to have this sort of feature to further configure mob spawning.

**Comment by Fuzss** [comment]
Which mob is that?

**Comment by ZerbieSlug** [comment]
The Atlatitan.

Their spawning mechanics are odd, and have specific requirements to even have them show up
(you need to defeat a boss to have them spawn, and they only spawn in an area where said boss is killed)

**Comment by ZerbieSlug** [comment]
Ok I made the mistake of playing version 8.1.1 while making this report, because in v8.2.0 this mob actually DOES despawn...

While I'm going to close this thread due to this, I still suggest having such a feature be added.
My apologies
