### ISSUE TITLE
[Bug]: Striders "overspawning"

### ISSUE THREAD

**Issue by Jacob8547** [Fuzss/respawninganimals#37]
### Mod Loader (Required)

Fabric

### Minecraft Version(s) (Required)

1.20.4

### Mod Version(s) (Required)

20.4.0

### Minimal Setup (Required)

Yes

### Notes (Required)

Current Behavior: Striders spawn indefinitely when high on the nether roof.

How to reproduce: Stand on a block at y=218 in a crimson forest on the nether roof. Wait untill thousands of striders have spawned.
![2024-06-19_15 46 08](https://github.com/Fuzss/respawninganimals/assets/156146733/21d008fa-e0bd-4bc7-82d5-987382b9d966)
![2024-06-19_15 46 42](https://github.com/Fuzss/respawninganimals/assets/156146733/7967f0d7-c36b-4059-bb76-bbbbada26b6b)

### latest.log (Required)

https://gist.github.com/Jacob8547/ba98e702d9e08e5b88222a46e9d83f77

**Comment by Fuzss** [comment]
Fixed in latest version for 1.20.1 & 1.21.1. 
1.20.4 is no longer supported unfortunately.
