### ISSUE TITLE
Respawnable Animals with Whisperwoods causes their mobs to respawn like crazy

### ISSUE THREAD

**Issue by BugmanBugman** [Fuzss/respawninganimals#5]
![image](https://user-images.githubusercontent.com/40730042/119699750-18d46f80-be18-11eb-864c-e7b618c2e3aa.png)
Could be the same issue as the endergetic one. It could be another mod  too, but the HG in particular overspawns like crazy. I believe this is because it may be marked as an animal, but its actually supposed to be a boss

**Comment by Fuzss** [comment]
Does blacklisting work?

**Comment by BugmanBugman** [comment]
Yeah seems to work so far. I’m just a bit confused since the Hirschgeist mob and the hidebehind mob are intended to be hostile and for the first one, a boss mob but they spawn like animals according this mod. Should I report this to the Whisperwoods GitHub tracker? Blacklisting seems to limit their spawning  entirely sadly.

**Comment by zPanic** [comment]
Old issue, but still open so...

I'm having the same issue with Alex's Mobs and Better Animals Plus..

**Comment by Fuzss** [comment]
Have you tried adding the problematic mobs to the blacklist?

**Comment by Fuzss** [comment]
Should be fixed in v8.1.0.
